"""empty message

Revision ID: 19397a7efd71
Revises: 8df60aa39a17
Create Date: 2022-03-09 17:15:57.026346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19397a7efd71'
down_revision = '8df60aa39a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('baths', sa.Integer(), nullable=True))
    op.drop_column('property', 'noOfRooms')
    op.drop_column('property', 'noOfBaths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('noOfBaths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('noOfRooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('property', 'baths')
    op.drop_column('property', 'rooms')
    # ### end Alembic commands ###
